410UPROGS = $(patsubst %,$(410UDIR)/$(UPROGDIR)/%,$(410REQPROGS) $(410TESTS))
STUUPROGS = $(patsubst %,$(STUUDIR)/$(UPROGDIR)/%,$(STUDENTREQPROGS) $(STUDENTTESTS))

410UCLEANS += $(410UPROGS)

ULIBS=$(410ULIBS_EARLY) $(STUULIBS_EARLY) $(410ULIBS_LATE) $(STUULIBS_LATE)
$(410UPROGS) $(EXTRA_410_PROGS): %: %.o $(CRT0) $(ULIBS)
	$(LD) $(LDFLAGS) -o $@ $< $(CRT0) --start-group $(ULIBS) --end-group

$(STUUPROGS): %: %.o $(CRT0) $(ULIBS)
	$(LD) $(LDFLAGS) -o $@ $< $(CRT0) --start-group $(ULIBS) --end-group
